# Generated by Django 5.1.2 on 2024-10-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKING', '0002_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp_token',
            name='otp_code',
            field=models.CharField(default='b00731', max_length=6),
        ),
    ]
