# Generated by Django 5.1.2 on 2024-10-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKING', '0003_alter_otp_token_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='moblie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otp_token',
            name='otp_code',
            field=models.CharField(default='5c5ba9', max_length=6),
        ),
    ]
