# Generated by Django 5.1.2 on 2024-10-16 06:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKING', '0004_alter_customuser_moblie_alter_otp_token_otp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='home')),
            ],
        ),
        migrations.CreateModel(
            name='Room_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(default=0, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='room')),
            ],
        ),
        migrations.AlterField(
            model_name='otp_token',
            name='otp_code',
            field=models.CharField(default='b8b622', max_length=6),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('time', models.TimeField(default=datetime.time(12, 0))),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOOKING.room_info')),
                ('room_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOOKING.rooms')),
            ],
        ),
    ]
